language: python
python: 2.7

install:
  - pip install ansible

  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
