---
# tasks file for ansible-role-swift
- name: Install dependencies
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Check if swift is installed
  command: "which swift"
  changed_when: false
  failed_when: false
  register: swift_installed

- name: Download PGP key
  get_url: url=https://swift.org/keys/all-keys.asc dest={{swift_tmp_directory}}
  when: swift_installed.rc == 1

- name: Add PGP key to keyring
  command: gpg --import {{swift_tmp_directory}}/{{swift_downloaded_pgp_key}}
  register: add_key
  changed_when: "'not changed' not in add_key.stderr"
  when: swift_installed.rc == 1

- name: Refresh keys
  command: gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
  changed_when: false
  when: swift_installed.rc == 1

- name: Download Swift
  get_url: url={{swift_package_url}} dest={{swift_tmp_directory}}/swift.tar.gz
  when: swift_installed.rc == 1

- name: Download signature
  get_url: url={{package_signature_url}} dest={{swift_tmp_directory}}/{{swift_signature_file_name}}
  when: swift_installed.rc == 1

- name: Verify signature
  command:  gpg --verify {{swift_tmp_directory}}/{{swift_signature_file_name}}
  register: verified_sig
  #Fails if gpg fails to verify and reports “BAD signature”
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  when: swift_installed.rc == 1

- name: Create swift install directory
  file: path={{swift_install_directory}} state=directory mode=0755
  when: swift_installed.rc == 1

- name: Extract the archive
  unarchive:
    src={{swift_tmp_directory}}/swift.tar.gz
    dest={{swift_install_directory}}
    copy=no
    creates={{swift_install_directory}}/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04
  when: swift_installed.rc == 1

- name: Modify PATH environment variable
  lineinfile: state=present line="export PATH={{swift_install_directory}}/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin:$PATH" dest=~/.bashrc
  when: swift_installed.rc == 1

- name: Remove downloaded key
  file: path={{swift_tmp_directory}}/{{swift_downloaded_pgp_key}} state=absent
  when: swift_installed.rc == 1

- name: Remove the other key
  file: path={{swift_tmp_directory}}/swift.tar.gz.sig state=absent
  when: swift_installed.rc == 1
